#
# Macro file for fast detector geometry
# Ag / PNDI-T10 / ITO / QuartzGlass with 14 MeV neutrons
#
/control/verbose 1
/run/verbose 1
#
/testhadr/det/setNbOfLayers 1
/testhadr/det/setNbOfAbsor 4
/testhadr/det/setAbsor 1 G4_Ag 40 nm
/testhadr/det/setAbsor 2 PNDI-T10 5 mm
/testhadr/det/setAbsor 3 ITO 100 nm
/testhadr/det/setAbsor 4 QuartzGlass 100 um
/testhadr/det/setSizeYZ 1 mm
#
/run/initialize
#
# Visualization
#/vis/open
#/vis/viewer/set/autoRefresh false
#/vis/verbose errors
#/vis/drawVolume
#/vis/viewer/zoom 1.2
#/vis/scene/add/trajectories smooth
#/vis/modeling/trajectories/create/drawByCharge
#/vis/scene/endOfEventAction accumulate
#/vis/viewer/set/autoRefresh true
#/vis/verbose warnings
#
# Override default GPS energy to 14 MeV
/gps/energy 14 MeV
#
#/run/printProgress 1000
/run/beamOn 1000000